[project]
name = "etl-project"
version = "0.1.0"
description = "Bootcamp projecto for Data engineering"
authors = ["mrGoonies <gooniesdev@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
dev = "cd app && uvicorn main:app"
check = "ruff check"
format = "ruff format"

[dependencies]
fastapi = ">=0.110.0,<0.111"
python = ">=3.12.2,<3.13"
ruff = ">=0.3.3,<0.4"
uvicorn = ">=0.28.0,<0.29"
